version: '3.6'

services:
  app:
    build:
      context: ./app
    container_name: nodeapp
    networks:
      - challenge-two
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - mysql
  
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - challenge-two
    ports:
      - 8080:80
      
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - challenge-two
    environment:
      - MYSQL_DATABASE=people
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - 3306:3306

networks:
  challenge-two:
    driver: bridge